### ISSUE TITLE
Receiving Push Notifications only when app is in foreground.

### ISSUE THREAD

**Issue by PPacie** [beaconinside/ios-sdk#10]
Xcode 9 - Swift 4
iOS 11.1.2/11.2.2 - iPhone5s
iOS 11.2.2 - iPhoneX

We haven't received any notifications when the app is in the background. 

Is it the default behavior to receive notifications only when the app is in the foreground? Can it be changed?

We have tested the BeaconInsideSDK in our project and also the Example project you have provided. Both projects have the same results (notification alerts only in foreground).

Thanks in advance.

**Comment by rabschi** [comment]
What kind of location opt-in do you use? Always or when-in-use? 

Did you implement the [BIBeaconService handleNotification] callback in the AppDelegate? 
https://github.com/beaconinside/ios-sdk#using-objective-c

**Comment by PPacie** [comment]
Hi @rabschi, thanks for the reply.

I have tested with 'Always' (as the documentation indicates). Should I use 'when-in-use'?

Yes, I have implemented the callbacks (Also I have tested with your demo project and it didn't work neither while the app is in background).

**Comment by rabschi** [comment]
Can you send me c.rabsch@beaconinside.com the Proximity DMP account email address and specify if you use geofences or beacons. Thanks

**Comment by PPacie** [comment]
Hi @rabschi I've sent the details this morning. Please let me know when you have any updates.
Thanks in advance.

**Comment by PPacie** [comment]
It seemed that the issue was in the beacons configuration that was updated recently. 
As could re-test today, with the same code implementation, the Beacon push notifications arrived even when the app is in background. 

Thanks @rabschi for the support.
