### ISSUE TITLE
Restart BeaconService

### ISSUE THREAD

**Issue by andreiChis70** [beaconinside/ios-sdk#12]
BeaconService - v2.10 (I cannot use higher because minimum ios version is 8.1)

I want to reinitialise (restart) BeaconService to find again the beacons.

This is what I did:
1. initBeaconService
2. At sometime in the app -> calling "terminate" + initBeaconService 

**Actual Behaviour**
I do not receive the beacons notifications again.

**Expected Behaviour**
I should find the beacons again and receive the notifications.

**Comment by rabschi** [comment]
Unfortunately we don't provide updates for version 2.10 but the intended use case for using the terminate function is to use it once in an apps lifecycle. That is the reason why the app could exhibit unexpected behaviour when the initialization is called right after terminating the SDK usage.
