### ISSUE TITLE
Airplane Mode - Beacon Detection

### ISSUE THREAD

**Issue by andreiChis70** [beaconinside/ios-sdk#13]
BeaconService - v2.11.1

It seems that beacon detection does not work when the device is in flight mode.
Now airplane mode does turn off location, bluetooth, ... but some of them you can turn back on.
I did turn location and bluetooth back on and there is no beacon detection. It should receive the signal from the beacon.

**Test: iPhone 6s - iOS 10.1**

I did test it in my project and in your example project. It does work when I'm offline but it does not work when I'm in flight mode.

Any idea how to fix this?

Thank you!

**Comment by rabschi** [comment]
In general it's possible but it's a rare use case often maybe not even wanted. Please send me an email to discuss relevance. cornelius@beaconinside.com
