### ISSUE TITLE
Crashing when there are no beacons nearby - BIRegionScanner.m:369

### ISSUE THREAD

**Issue by PPacie** [beaconinside/ios-sdk#9]
Xcode 9 - Swift 4 - iOS 11.1.2 - iPhone5s

It happens when opening the app and there are no beacons nearby. If you have beacons nearby it doesn't crash. 
This is also happening in your example app **BeaconServiceExample-Swift**.

**Error:** 
Fatal Exception: NSRangeException
*** -[__NSArrayM objectAtIndex:]: index 10 beyond bounds [0 .. 9]
in -[BIRegionScanner getReloadGeofenceForGeofences:] (BIRegionScanner.m:369)

Fatal Exception: NSRangeException
0  CoreFoundation                 0x184411d04 __exceptionPreprocess
1  libobjc.A.dylib                0x183660528 objc_exception_throw
2  CoreFoundation                 0x1843aabd4 _CFArgv
3  CoreFoundation                 0x1842da9a0 -[__NSArrayM removeObjectAtIndex:]
**4  app                        0x1000d532c -[BIRegionScanner getReloadGeofenceForGeofences:] (BIRegionScanner.m:369)**
5  app                        0x1000d4c80 -[BIRegionScanner startGeofenceMonitoring] (BIRegionScanner.m:307)
6  app                        0x1000d55bc -[BIRegionScanner locationManager:didUpdateLocations:] (BIRegionScanner.m:440)
7  CoreLocation                   0x18a97ed28 (null)
8  CoreLocation                   0x18a97e588 (null)
9  CoreLocation                   0x18a966c08 (null)
10 CoreFoundation                 0x1843ba0fc __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__
11 CoreFoundation                 0x1843b99cc __CFRunLoopDoBlocks
12 CoreFoundation                 0x1843b7c34 __CFRunLoopRun
13 CoreFoundation                 0x1842d7fb8 CFRunLoopRunSpecific
14 GraphicsServices               0x18616ff84 GSEventRunModal
15 UIKit                          0x18d8ac2e8 UIApplicationMain
16 app                       0x1000b94d4 main (AppDelegate.swift:16)
17 libdyld.dylib                  0x183dfa56c start

**Comment by rabschi** [comment]
Outdated, fixed by now.
